User.create!(username: "Welcome!", password: "39cn109283e01wjc1owhd10v10wmdjskanlkaj0dw19x1")
User.create!(username: "ShyGuy", password: "password")
User.create!(username: "Sunny", password: "efijo[wfiejaniceo2nce")
User.create!(username: "Bryan792", password: "1couiwcm1odm1jad")
User.create!(username: "smartglo1", password: "pas1923r0sword")
User.create!(username: "vect", password: "1iohf1c0293ndru901")
User.create!(username: "AndyEskimo", password: "12039den1209ineu1on")
User.create!(username: "Silkwood", password: "x193n4rc189n3")
User.create!(username: "trollinh", password: "12iowjedn1xlkemdo")
User.create!(username: "Sabbsie", password: "v31oiuvn1peonvp1")
User.create!(username: "yuki", password: "dejkcalkjdlfc")
User.create!(username: "torinro", password: "1v2904nv10298vn1")
User.create!(username: "Superjova", password: "efijo[wfiejaniceo2nce")
User.create!(username: "ArgMikey|Pengwins", password: "1couiwcm1odm1jad")
User.create!(username: "Aerinyes", password: "pas1923r0sword")
User.create!(username: "Sydor", password: "1iohf1c0293ndru901")
User.create!(username: "CorgiBooty", password: "12039den1209ineu1on")
User.create!(username: "Starwood", password: "x193n4rc189n3")
User.create!(username: "CavalierGuest", password: "12iowjedn1xlkemdo")
User.create!(username: "chronation", password: "efijo[wfiejaniceo2nce")
User.create!(username: "DemonicRabbit", password: "1couiwcm1odm1jad")
User.create!(username: "Handlebars", password: "pas1923r0sword")
User.create!(username: "diverges", password: "1iohf1c0293ndru901")
User.create!(username: "AfricaLionSafari", password: "12039den1209ineu1on")
User.create!(username: "bottomlessfries", password: "x193n4rc189n3")
User.create!(username: "Tom the Tomato", password: "12iowjedn1xlkemdo")
User.create!(username: "EKevin", password: "1couiwcm1odm1jad")
User.create!(username: "Oddish", password: "pas1923r0sword")
User.create!(username: "Blades", password: "1iohf1c0293ndru901")
User.create!(username: "rentaro", password: "12039den1209ineu1on")
User.create!(username: "ohmygosher", password: "12iowjedn1xlkemdo")
User.create!(username: "Fain", password: "12iowjedn1xlkemdo")
User.create!(username: "Aryssalis", password: "efijo[wfiejaniceo2nce")
User.create!(username: "KNIP", password: "1couiwcm1odm1jad")
User.create!(username: "Blackstabath", password: "pas1923r0sword")
User.create!(username: "show7ime", password: "1iohf1c0293ndru901")
User.create!(username: "Remiflan", password: "12039den1209ineu1on")
User.create!(username: "milkNcookies", password: "x193n4rc189n3")
User.create!(username: "Arty1901", password: "12iowjedn1xlkemdo")
User.create!(username: "valeriethequeenofsmack", password: "testing")

Channel.create!(admin_id: 2, title: "fremont", description: "", icon_url: "https://cdn.discordapp.com/icons/91722996300943360/fd7a1d84d586eaba09e0a38e0c5280ed.jpg")
Channel.create!(admin_id: 13, title: "Chairleague", description: "", icon_url: "https://cdn.discordapp.com/icons/134600616818245633/7f4257ed06f6e5ae80622e7816e91489.jpg")
Channel.create!(admin_id: 20, title: "Veggie Tales", description: "", icon_url: "https://cdn.discordapp.com/icons/152604801484455936/2fc30d67d9db688a36c3cb0f17143683.jpg")
Channel.create!(admin_id: 27, title: "Educational Scrims", description: "", icon_url: "")
Channel.create!(admin_id: 34, title: "TSM", description: "", icon_url: "http://www.esports-betting.pro/wp-content/uploads/2014/05/Logo-of-LCS-NA-Summer-Split-Team-TSM-64.png")

Subscription.create!(user_id: 2, channel_id: 1)
Subscription.create!(user_id: 3, channel_id: 1)
Subscription.create!(user_id: 4, channel_id: 1)
Subscription.create!(user_id: 5, channel_id: 1)
Subscription.create!(user_id: 6, channel_id: 1)
Subscription.create!(user_id: 7, channel_id: 1)
Subscription.create!(user_id: 8, channel_id: 1)
Subscription.create!(user_id: 9, channel_id: 1)
Subscription.create!(user_id: 10, channel_id: 1)
Subscription.create!(user_id: 11, channel_id: 1)
Subscription.create!(user_id: 12, channel_id: 1)
Subscription.create!(user_id: 40, channel_id: 1)

Subscription.create!(user_id: 13, channel_id: 2)
Subscription.create!(user_id: 14, channel_id: 2)
Subscription.create!(user_id: 15, channel_id: 2)
Subscription.create!(user_id: 2, channel_id: 2)
Subscription.create!(user_id: 16, channel_id: 2)
Subscription.create!(user_id: 17, channel_id: 2)
Subscription.create!(user_id: 18, channel_id: 2)
Subscription.create!(user_id: 19, channel_id: 2)

Subscription.create!(user_id: 20, channel_id: 3)
Subscription.create!(user_id: 21, channel_id: 3)
Subscription.create!(user_id: 22, channel_id: 3)
Subscription.create!(user_id: 23, channel_id: 3)
Subscription.create!(user_id: 24, channel_id: 3)
Subscription.create!(user_id: 25, channel_id: 3)
Subscription.create!(user_id: 2, channel_id: 3)
Subscription.create!(user_id: 26, channel_id: 3)

Subscription.create!(user_id: 27, channel_id: 4)
Subscription.create!(user_id: 28, channel_id: 4)
Subscription.create!(user_id: 2, channel_id: 4)
Subscription.create!(user_id: 29, channel_id: 4)
Subscription.create!(user_id: 30, channel_id: 4)
Subscription.create!(user_id: 31, channel_id: 4)
Subscription.create!(user_id: 32, channel_id: 4)

Subscription.create!(user_id: 33, channel_id: 5)
Subscription.create!(user_id: 34, channel_id: 5)
Subscription.create!(user_id: 35, channel_id: 5)
Subscription.create!(user_id: 36, channel_id: 5)
Subscription.create!(user_id: 37, channel_id: 5)
Subscription.create!(user_id: 38, channel_id: 5)
Subscription.create!(user_id: 39, channel_id: 5)
Subscription.create!(user_id: 2, channel_id: 5)

TextChannel.create!(channel_id: 1, title: "general", description: "If you want to get added to a game (hots,ow) specific channel, ask @Sunny or @Bryan792")
Message.create!(author_id: 1, body: "This is the beginning of the #general channel.", chatable_id: 1, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "chingus", description: "No nugus here")
Message.create!(author_id: 1, body: "This is the beginning of the #chingus channel.", chatable_id: 2, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "bamf", description: "For Chairleague specific chat")
Message.create!(author_id: 1, body: "This is the beginning of the #bamf channel.", chatable_id: 3, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "overwatch", description: "🐉 🐉 🐉 RYU GA WAGA TEKI WO KURAU! 🐉 🐉 🐉")
Message.create!(author_id: 1, body: "This is the beginning of the #overwatch channel.", chatable_id: 4, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "smash", description: "get smashed")
Message.create!(author_id: 1, body: "This is the beginning of the #smash channel.", chatable_id: 5, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "brybotland", description: "welcome to BryBot Land")
Message.create!(author_id: 1, body: "This is the beginning of the #brybotland channel.", chatable_id: 6, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "meow", description: "meow meow meow ^ↀᴥↀ^")
Message.create!(author_id: 1, body: "This is the beginning of the #meow channel.", chatable_id: 7, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 1, title: "music", description: "♬ ♪ ♫ Post and share music links here! ♫ ♪ ♬")
Message.create!(author_id: 1, body: "This is the beginning of the #music channel.", chatable_id: 8, chatable_type: "TextChannel")

TextChannel.create!(channel_id: 2, title: "general", description: "Regular discussion; hangout and talk about whatever you'd like!")
Message.create!(author_id: 1, body: "This is the beginning of the #general channel.", chatable_id: 9, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "welcome", description: "Welcome to the channel, quick message below!")
Message.create!(author_id: 1, body: "This is the beginning of the #welcome channel.", chatable_id: 10, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "registration", description: "Post in here to get your Discord Role! If you're a registered player, type Player. If you're an active caster, type Caster")
Message.create!(author_id: 1, body: "This is the beginning of the #registration channel.", chatable_id: 11, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "announcements", description: "Stuff such as schedules, special games, or Chair League news will be posted to everyone here!")
Message.create!(author_id: 1, body: "This is the beginning of the #announcements channel.", chatable_id: 12, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "looking4casters", description: "A place to find a Caster for your Match or Scrim and for Casters to post availability!")
Message.create!(author_id: 1, body: "This is the beginning of the #looking4casters channel.", chatable_id: 13, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "scrims", description: "If you're looking for somebody to help scrim or fill in, post here. Or use the site's official scrim tool!")
Message.create!(author_id: 1, body: "This is the beginning of the #scrims channel.", chatable_id: 14, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "pick-up", description: "Want to play some Hero/Team League with someone new or just hop in some Quick Match? Post here!")
Message.create!(author_id: 1, body: "This is the beginning of the #pick-up channel.", chatable_id: 15, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "service-desk", description: "If you need help with anything, post here and it'll get sorted right away.")
Message.create!(author_id: 1, body: "This is the beginning of the #service-desk channel.", chatable_id: 16, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 2, title: "free-agents", description: "Your team needs another member? You need a team? Look no further!")
Message.create!(author_id: 1, body: "This is the beginning of the #free-agents channel.", chatable_id: 17, chatable_type: "TextChannel")

TextChannel.create!(channel_id: 3, title: "general", description: "")
Message.create!(author_id: 1, body: "This is the beginning of the #general channel.", chatable_id: 18, chatable_type: "TextChannel")

TextChannel.create!(channel_id: 4, title: "general", description: "welcome")
Message.create!(author_id: 1, body: "This is the beginning of the #general channel.", chatable_id: 19, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 4, title: "replayshare", description: "share replays and help analyze")
Message.create!(author_id: 1, body: "This is the beginning of the #replayshare channel.", chatable_id: 20, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 4, title: "discussionarea", description: "post-game discussion")
Message.create!(author_id: 1, body: "This is the beginning of the #discussionarea channel.", chatable_id: 21, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 4, title: "lfscrims", description: "set up scrims here")
Message.create!(author_id: 1, body: "This is the beginning of the #lfscrims channel.", chatable_id: 22, chatable_type: "TextChannel")
TextChannel.create!(channel_id: 4, title: "tournamentdiscussion", description: "watch broadcasts/tourneys together")
Message.create!(author_id: 1, body: "This is the beginning of the #tournamentdiscussion channel.", chatable_id: 23, chatable_type: "TextChannel")

TextChannel.create!(channel_id: 5, title: "general", description: "T S M T S M T S M T S M T S M T S M T S M T S M T S M T S M ")
Message.create!(author_id: 1, body: "This is the beginning of the #general channel.", chatable_id: 24, chatable_type: "TextChannel")

DirectMessage.create!(speaker_id: 2, listener_id: 4)
Message.create!(author_id: 4, body: "I think, going forward, we should just have the people who are playing hots most often be regulars on the team and have everyone else be subs", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "Kk then we need to decide if that is David or Blee", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "they can alternate", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "Cause they are both mia as ffuuuhhh", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "Ah okay", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "btw did you say that you feel like kelvin shouldn't be solo tank?", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "in the google sheet I have me as solo tank and kelvin as flex", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "but now that I think about it, I feel like it'd be better if I was flex because of how deep my hero pool is", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "id rather have you as solo tank or as a tank/bruiser in a 2 warrior comp", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "hm okay", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "we'll make it work somehow", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "my only concern is if zag is still in the pool", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "?", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "zag too good", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "ah yeah very possible that they'll take it during their first pick phase", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 2, body: "do we want to ban first-ban rehgar btw?", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "hmm", chatable_type: "DirectMessage", chatable_id: 1)
Message.create!(author_id: 4, body: "maybe ban kt", chatable_type: "DirectMessage", chatable_id: 1)

DirectMessage.create!(speaker_id: 7, listener_id: 2)
Message.create!(author_id: 7, body: "is sabbsie anyone i know", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "ahh no", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "he probably played with us in OW though", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "he's bryan's friend's friend", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 7, body: "oic lol", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "and hes a smasher?", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "yeah apparently he streams too haha", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 2, body: "must be pretty good", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 7, body: "o dayum", chatable_type: "DirectMessage", chatable_id: 2)
Message.create!(author_id: 7, body: "cool", chatable_type: "DirectMessage", chatable_id: 2)

DirectMessage.create!(speaker_id: 5, listener_id: 2)
Message.create!(author_id: 2, body: "yo louis", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "Yo", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "Wassup", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "so I have logitech g35 headphones", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "and was wondering if you have the same problem with your headphones", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "where the audio for youtube is super quiet for some reason", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "i've looked it up and people have had the same issue for years", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "but I haven't found a fix for it", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "i used to have the problem with my g930s", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "and i just kinda switched to spekaers when i would watch youtube", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "and then i stopped using them", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "so i can't erally say there's a fix", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "lol", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "damn haha", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "that's unfortunate", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "btw I kidna figured out how to fix the logitech headphone issue'", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "you have to click on the sound icon in the bottom right and click on mixer", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "and adjust it for chrome", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 2, body: "have to do it every once in a while...", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "I see", chatable_type: "DirectMessage", chatable_id: 3)
Message.create!(author_id: 5, body: "Interesting", chatable_type: "DirectMessage", chatable_id: 3)

DirectMessage.create!(speaker_id: 40, listener_id: 2)
Message.create!(author_id: 40, body: "who want mickey D's", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 2, body: "me me me!", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 2, body: "wait for me", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 40, body: "omg you are a fattie", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 2, body: "taco bell rules", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 40, body: "how was last night", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 40, body: "Eli Im asking you a question!!!", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 40, body: "hello?", chatable_type: "DirectMessage", chatable_id: 4)
Message.create!(author_id: 40, body: "alright im done", chatable_type: "DirectMessage", chatable_id: 4)

DirectMessage.create!(speaker_id: 38, listener_id: 2)
Message.create!(author_id: 38, body: "wanna play some hots?", chatable_type: "DirectMessage", chatable_id: 5)
Message.create!(author_id: 2, body: "sure", chatable_type: "DirectMessage", chatable_id: 5)

DirectMessage.create!(speaker_id: 2, listener_id: 31)
Message.create!(author_id: 2, body: "Hey, ohmygosher, this is the captain of Ben's Awesome Mephistophilean Friends", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 2, body: "Just wanted to give you a heads up that our team is trying to reschedule our match versus Squirtle Squad at 7 PM tonight to tomorrow at the same time", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 31, body: "ok", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 2, body: "Squirtle Squad's captain said that they are okay with rescheduling, right now I'm trying to get in contact with superjova", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 31, body: "alright, i can cast it tomorrow too", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 2, body: "Okay, awesome, do you know if we need Superjova to approve of the match change? Or do we just go through with it?", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 2, body: "Given that the teams + caster are okay with it?", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 31, body: "Just let him know on Discord, should be ok though.", chatable_type: "DirectMessage", chatable_id: 6)
Message.create!(author_id: 2, body: "Alright, I'll keep you updated", chatable_type: "DirectMessage", chatable_id: 6)

DirectMessage.create!(speaker_id: 22, listener_id: 2)
Message.create!(author_id: 2, body: "yo ggs they were fun today", chatable_type: "DirectMessage", chatable_id: 7)
Message.create!(author_id: 22, body: "yeah np gg", chatable_type: "DirectMessage", chatable_id: 7)
Message.create!(author_id: 2, body: "see you next week", chatable_type: "DirectMessage", chatable_id: 7)

DirectMessage.create!(speaker_id: 2, listener_id: 3)
Message.create!(author_id: 2, body: "yo ben", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "with this tournament thing, would you want to cast with me?", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "i'm anticipating open bracket, rank 15 and below bracket, and rank 30 and below bracket", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "or maybe open, 10, 20, 30", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "but either way we can participate and cast as well", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "ben", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 2, body: "game or no", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 3, body: "whats this", chatable_type: "DirectMessage", chatable_id: 8)
Message.create!(author_id: 3, body: "join the server?", chatable_type: "DirectMessage", chatable_id: 8)
